export const addDataTab = "Adatok felvétele";
export const addNewAddressButton = "Új cím";
export const addNewPhoneButton = "Új telefonszám"
export const browseModifyDataTab = "Adatok megtekintése/szerkesztése";
export const city = "Város";
export const dateOfBirth = "Születés helye";
export const del = "Törlés";
export const emailAddress = "E-mail cím";
export const houseNumber = "Házszám";
export const missingOrInvalidValue = "Hiányzó vagy hibás érték";
export const motherName = "Anyja születési neve";
export const name = "Név";
export const phoneNumber = "Telefonszám";
export const placeOfBirth = "Születés helye";
export const postalCode = "Irányítószám";
export const save = "Mentés";
export const street = "Utca";
export const tajNumber = "TAJ szám";
export const taxIdentifier = "Adóazonosító jel";