version: '2'

services:
  app:
    image: 'dpd-docker-spring-boot-react-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dpd
      - SPRING_DATASOURCE_USERNAME=dpd
      - SPRING_DATASOURCE_PASSWORD=dpd
      - SPRINT_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "127.0.0.1:8080:8080"
  db:
    image: 'postgres:13.2-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=dpd
      - POSTGRES_PASSWORD=dpd